### ISSUE TITLE
Netherlands request

### ISSUE THREAD

**Issue by tristan-deep** [oisincar/imois.in#8]
Love the game, we need a Netherlands version too! 🇳🇱

**Comment by oisincar** [comment]
Hi. Sure, why not!

What divisions make sense? I think the 12 Provinces mightn't be enough for an interesting route each day - unless the game becomes 'name a provenance between X and Y'. Would people know the Municipalities?

P.S. Lots of people from the Netherlands played travle yesterday - more than any other country..! Any idea what happened?

**Comment by tristan-deep** [comment]
Awesome! Agree, 12 provinces are too easy. Municipalities would be hard, but still interesting I think! Netherlands was part of the challenge yesterday, that might have something to do with it?

edit: I see the municipalities [here](https://upload.wikimedia.org/wikipedia/commons/3/33/2023-NL-Gemeenten-basis-2500px.png). Looks like there are about 300.

**Comment by fwdekker** [comment]
I think 12 provinces are too easy, but the 300+ municipalities might be a bit much. Even France has "only" 96 areas to choose from.

Maybe include the entire Benelux instead? Belgium has 10 provinces, and Luxembourg has 3 districts, for a total of 25 regions making up the map. (Using the 12 cantons of Luxembourg feels a bit disproportional compared to the sizes of the others' 22 provinces.)

**Comment by oisincar** [comment]
I went with the Benelux idea, it should be live in the next few hours!

There were a few interesting cases - e.g. Limburg is in both the Netherlands and Belgium, so I put 'Limburg (Netherlands)' and 'Limburg (Belgium)' as separate regions, which hopefully is reasonable. There is the same for Luxembourg.

Thanks for the suggestions!

**Comment by oisincar** [comment]
I went with the Benelux idea, it should be live in the next few hours!

There were a few interesting cases - e.g. Limburg is in both the Netherlands and Belgium, so I put 'Limburg (Netherlands)' and 'Limburg (Belgium)' as separate regions, which hopefully is reasonable. There is the same for Luxembourg.

Thanks for the suggestions!

**Comment by fwdekker** [comment]
Welp, I just played the Benelux version for a bit, and found out I really know my neighbouring country Belgium's provinces a lot worse than I thought. Thank you for adding it! :)

If you're interested I also have some feedback/nitpicks about this version:
1. For gameplay reasons, I think it'd be better to exclude the Netherlands' Caribbean islands (Bonaire, Saba, and Sint Eustatius), even though they are technically part of the Benelux.
2. Most Belgian provinces have different names in different languages, all of which are canonical (because Belgium has three official languages). For example, Liège is also known as Luik in Dutch and Lüttich in German. ([Wikipedia has a table listing all provinces and their various names.](https://en.wikipedia.org/wiki/Provinces_of_Belgium)) I think it would be worthwhile to invest in creating a system (for the game in general) that recognises alternative names for places. (Perhaps this should be put in a separate issue?) I'd suggest that the search bar still only displays the English name, but matches on both the English name and local names. So if I enter "Lu" I see "**Lu**xembourg (Belgium)", "**Lu**xembourg (Luxembourg)", and "Liège" (for "**Lu**ik"). No need to include every translations from every language in the world, of course, but for multilingual countries I think this is important.

**Comment by tristan-deep** [comment]
> I went with the Benelux idea, it should be live in the next few hours!
> 
> There were a few interesting cases - e.g. Limburg is in both the Netherlands and Belgium, so I put 'Limburg (Netherlands)' and 'Limburg (Belgium)' as separate regions, which hopefully is reasonable. There is the same for Luxembourg.
> 
> Thanks for the suggestions!

Amazing, thanks for the work @oisincar!

**Comment by oisincar** [comment]
> 1. I think it'd be better to exclude the Netherlands' Caribbean islands

They're there as guessable regions, but they can't show up in puzzles. I guess it's similar to islands being in the 'regular' travle, too. (Or are they interfering in another way?)


> 2 [..] search bar still only displays the English name, but matches on both the English name and local names.

That's a good idea! All travle versions should probably let you enter the local names of regions, too. That said, Travle's also available in a large number of languages (if you didn't know)! You can play the game in Dutch or German already (including the new benelux version), with local place names from those regions. Of course that only works if you're happy to commit to naming the places in one specific language.

**Comment by fwdekker** [comment]
> They're there as guessable regions, but they can't show up in puzzles. I guess it's similar to islands being in the 'regular' travle, too. (Or are they interfering in another way?)

Fair enough. I brought it up because I accidentally selected Saba yesterday, but then the game couldn't quite zoom in far enough to comfortably show the Benelux again :P

> That's a good idea! All travle versions should probably let you enter the local names of regions, too. That said, Travle's also available in a large number of languages (if you didn't know)! You can play the game in Dutch or German already (including the new benelux version), with local place names from those regions. Of course that only works if you're happy to commit to naming the places in one specific language.

Oh, I didn't know that! That's very nice :-) At least for the Benelux that solves the issue for me, though I think allowing local languages would still be a nice feature to have

**Comment by oisincar** [comment]
> Fair enough. I brought it up because I accidentally selected Saba yesterday, but then the game couldn't quite zoom in far enough to comfortably show the Benelux again :P

That's very fair. If it happens again (and this is also not obvious) you can click your guess to hide it from the map.
