### ISSUE TITLE
[travle] Travle USA incorrectly claims you can diagonally cross the Four Corner States.

### ISSUE THREAD

**Issue by shrx** [oisincar/imois.in#9]
Travle USA incorrectly claims you can diagonally cross the Four Corner States, for example from Utah to New Mexico.

**Comment by oisincar** [comment]
'Corners count' is an intentional rule! You can step from one state to the other without stepping in another. It's noted in the extra_info page, too.

I'd completely understand if it's one of the more contentious rules, but there was a little discussion on the subreddit about it that seemed fairly split (with some people citing legal proceedings that talked about adjacency), so I decided to leave it as-is.
